package standard

import (
	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/appends"
	"golang.org/x/tools/go/analysis/passes/asmdecl"
	"golang.org/x/tools/go/analysis/passes/assign"
	"golang.org/x/tools/go/analysis/passes/atomic"
	"golang.org/x/tools/go/analysis/passes/atomicalign"
	"golang.org/x/tools/go/analysis/passes/bools"
	"golang.org/x/tools/go/analysis/passes/buildssa"
	"golang.org/x/tools/go/analysis/passes/buildtag"
	"golang.org/x/tools/go/analysis/passes/cgocall"
	"golang.org/x/tools/go/analysis/passes/composite"
	"golang.org/x/tools/go/analysis/passes/copylock"
	"golang.org/x/tools/go/analysis/passes/ctrlflow"
	"golang.org/x/tools/go/analysis/passes/deepequalerrors"
	"golang.org/x/tools/go/analysis/passes/defers"
	"golang.org/x/tools/go/analysis/passes/directive"
	"golang.org/x/tools/go/analysis/passes/errorsas"
	"golang.org/x/tools/go/analysis/passes/fieldalignment"
	"golang.org/x/tools/go/analysis/passes/findcall"
	"golang.org/x/tools/go/analysis/passes/framepointer"
	"golang.org/x/tools/go/analysis/passes/gofix"
	"golang.org/x/tools/go/analysis/passes/hostport"
	"golang.org/x/tools/go/analysis/passes/httpmux"
	"golang.org/x/tools/go/analysis/passes/httpresponse"
	"golang.org/x/tools/go/analysis/passes/ifaceassert"
	"golang.org/x/tools/go/analysis/passes/inspect"
	"golang.org/x/tools/go/analysis/passes/loopclosure"
	"golang.org/x/tools/go/analysis/passes/lostcancel"
	"golang.org/x/tools/go/analysis/passes/nilfunc"
	"golang.org/x/tools/go/analysis/passes/nilness"
	"golang.org/x/tools/go/analysis/passes/pkgfact"
	"golang.org/x/tools/go/analysis/passes/printf"
	"golang.org/x/tools/go/analysis/passes/reflectvaluecompare"
	"golang.org/x/tools/go/analysis/passes/shadow"
	"golang.org/x/tools/go/analysis/passes/shift"
	"golang.org/x/tools/go/analysis/passes/sigchanyzer"
	"golang.org/x/tools/go/analysis/passes/slog"
	"golang.org/x/tools/go/analysis/passes/sortslice"
	"golang.org/x/tools/go/analysis/passes/stdmethods"
	"golang.org/x/tools/go/analysis/passes/stdversion"
	"golang.org/x/tools/go/analysis/passes/stringintconv"
	"golang.org/x/tools/go/analysis/passes/structtag"
	"golang.org/x/tools/go/analysis/passes/testinggoroutine"
	"golang.org/x/tools/go/analysis/passes/tests"
	"golang.org/x/tools/go/analysis/passes/timeformat"
	"golang.org/x/tools/go/analysis/passes/unmarshal"
	"golang.org/x/tools/go/analysis/passes/unreachable"
	"golang.org/x/tools/go/analysis/passes/unsafeptr"
	"golang.org/x/tools/go/analysis/passes/unusedresult"
	"golang.org/x/tools/go/analysis/passes/unusedwrite"
	"golang.org/x/tools/go/analysis/passes/usesgenerics"
	"golang.org/x/tools/go/analysis/passes/waitgroup"
)

var Analyzers = []*analysis.Analyzer{
	appends.Analyzer,
	bools.Analyzer,
	copylock.Analyzer,
	errorsas.Analyzer,
	hostport.Analyzer,
	pkgfact.Analyzer,
	shift.Analyzer,
	stdversion.Analyzer,
	timeformat.Analyzer,
	unusedwrite.Analyzer,
	asmdecl.Analyzer,
	buildssa.Analyzer,
	ctrlflow.Analyzer,
	fieldalignment.Analyzer,
	httpmux.Analyzer,
	loopclosure.Analyzer,
	printf.Analyzer,
	sigchanyzer.Analyzer,
	stringintconv.Analyzer,
	unmarshal.Analyzer,
	usesgenerics.Analyzer,
	assign.Analyzer,
	buildtag.Analyzer,
	deepequalerrors.Analyzer,
	findcall.Analyzer,
	httpresponse.Analyzer,
	lostcancel.Analyzer,
	slog.Analyzer,
	structtag.Analyzer,
	unreachable.Analyzer,
	waitgroup.Analyzer,
	atomic.Analyzer,
	cgocall.Analyzer,
	defers.Analyzer,
	framepointer.Analyzer,
	ifaceassert.Analyzer,
	nilfunc.Analyzer,
	reflectvaluecompare.Analyzer,
	sortslice.Analyzer,
	testinggoroutine.Analyzer,
	unsafeptr.Analyzer,
	atomicalign.Analyzer,
	composite.Analyzer,
	directive.Analyzer,
	gofix.Analyzer,
	inspect.Analyzer,
	nilness.Analyzer,
	shadow.Analyzer,
	stdmethods.Analyzer,
	tests.Analyzer,
	unusedresult.Analyzer,
}
