force-file-write: true
template: matryer
structname: "{{.Mock}}{{.InterfaceName | firstUpper}}"
  
packages:
  github.com/PiskarevSA/go-advanced/internal/handlers:
    interfaces:
      metricsUsecase:
  github.com/PiskarevSA/go-advanced/internal/usecases:
    interfaces:
      storage: